### ISSUE TITLE
problem with keybindings

### ISSUE THREAD

**Issue by sebastinas** [bpython/bpython#447]
With
```
[keyboard]
help = F2
show_source = F9
```
F2 is stilled mapped to `show_source`.

**Comment by thomasballinger** [comment]
Ugh this is terrible code that I wrote.

The current behavior of the local function `get_key_no_doublebind` isn't quite right, but the desired behavior should be:

* if there's a custom key specified for an action and that key has a different current use that is a default, delete that default use
* if there's a custom key specified for an action and that key has a different current use that is not a default, it must have been speficied in the config file; raise an error.

The function should be made module-level instead of local and tested. @keyanP is looking at this now.

**Comment by thomasballinger** [comment]
Something like
~~~.py
    def get_key_no_doublebind(attr, already_used={}):
        """Clears any other configured keybindings using this key

        already_used maps keys to their uses
        """
        key = config.get('keyboard', attr)
        if key in already_used:
            previous_use_of_key_is_a_default = defaults['keyboard'][already_used[key]] == key
            if previous_use_of_key_is_a_default:
                setattr(struct, '%s_key' % already_used[key], '')
            else:
                raise ValueError("config specified the key %r twice: for %s and %s" %
                                 (key, already_used[key], attr))
        if key: #prevents empty string from going in, which *can* be doublebound
            already_used[key] = attr
        return key
~~~
but should be a global function, should be more explicit about state (probably a class?) and should is finicky enough to warrant some TDD.

**Comment by keyanp** [comment]
So this change passes the tests and the specific case here, but still doesn't address the second point Tom made: "if there's a custom key specified for an action and that key has a different current use that is not a default, it must have been specified in the config file; raise an error".

Also I think I didn't update my master branch before making the pull request, because the Travis build failed because of some old code from when I was fixing #442.

**Comment by sebastinas** [comment]
Thank you for working on this issue. The Travis build failure seems to be caused by #452.

I've pushed new tests and commeted on the pull request. Could you please check if your changes still pass the test suite and address the comment?
