### ISSUE TITLE
Ctrl-Y in OS X causes bpython to suspend

### ISSUE THREAD

**Issue by amjith** [bpython/bpython#507]
When I'm in bpython repl I used to press Ctrl-y to paste stuff from my yank-ring.

But with the new curtsies UI, when I press C-y bpython is suspended. When I type `fg` to bring it to foreground it crashes. 

```
[~]
$ bpython
bpython version 0.14.1 on top of Python 2.7.9 /usr/local/opt/python/bin/python2.7
>>>

[1]  + 35719 suspended  bpython
FAIL: 18

[~]
$
zsh: you have suspended jobs.
FAIL: 18

[~]
$ fg
[1]  + 35719 continued  bpython

Traceback (most recent call last):
  File "/usr/local/bin/bpython", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsies.py", line 79, in main
    interactive=(not exec_args))
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsies.py", line 172, in mainloop
    e = input_generator.send(0)
  File "/usr/local/lib/python2.7/site-packages/curtsies/input.py", line 128, in send
    return self._send(timeout)
  File "/usr/local/lib/python2.7/site-packages/curtsies/input.py", line 179, in _send
    assert num_bytes > 0, num_bytes
AssertionError: 0
FAIL: 1
```

If I suspend it using C-z, I'm able to resume it without trouble when I do `fg`. 

I tried this in a linux machine (via docker) and Ctrl-y seems to be working fine.

**Comment by thomasballinger** [comment]
I can't replicate this - perhaps you have something like "stty susp CTRL-Y" or "stty dsusp CTRL-Y" somewhere in your shell config file? bpython-curses (old bpython) ignores these signals I think.

**Comment by thomasballinger** [comment]
I believe the current behavior is correct (things like `cat` behave similarly) but maybe we could ignore this signal most of the time?

**Comment by thomasballinger** [comment]
Whoops, maybe the is the default behavior or ctrl-y and I just have it turned off. I believe this is a bug now.

**Comment by sebastinas** [comment]
Why would we want to ignore it? If the user sends a signal to suspend the process we should handle it.

**Comment by thomasballinger** [comment]
python exits (crashes?) for me after foregrounding after ctrl-Y, IPython ignores it somehow. I agree we should handle it.

>SUSP
(Control-z or ASCII SUB ) generates a SIGTSTP signal. SIGTSTP stops all processes in the foreground process group for that terminal.

>DSUSP
(Control-y or ASCII EM ) It generates a SIGTSTP signal as SUSP does, but the signal is sent when a process in the foreground process group attempts to read the DSUSP character, rather than when it is typed.

So curtsies should needs to be ok with being suspended when it tried to read. This is a curtsies bug, fixable by removing two assertions in the code because I thought the was impossible:

~~~
(bpython0.14)tom-mba:curtsies tomb$ git diff
diff --git a/curtsies/input.py b/curtsies/input.py
index 7f21a06..b2db411 100644
--- a/curtsies/input.py
+++ b/curtsies/input.py
@@ -196,7 +196,7 @@ class Input(object):
             return None

         num_bytes = self._nonblocking_read()
-        assert num_bytes > 0, num_bytes
+        #assert num_bytes > 0, num_bytes
         if self.paste_threshold is not None and num_bytes > self.paste_threshold:
             paste = events.PasteEvent()
             while True:
@@ -209,7 +209,7 @@ class Input(object):
                     paste.events.append(e)
         else:
             e = find_key()
-            assert e is not None
+            #assert e is not None
             return e

     def _nonblocking_read(self):
(bpython0.14)tom-mba:curtsies tomb$
~~~

**Comment by thomasballinger** [comment]
https://github.com/thomasballinger/curtsies/compare/fix-ctrl-y fixes this, any thoughts?

**Comment by amjith** [comment]
I'd recommend ignoring the C-Y (dsusp signal). 

Excerpt from the man pages of termios. 
```
VDSUSP (not in POSIX; not supported under Linux; 031, EM, Ctrl-Y) Delayed suspend character: send SIGTSTP signal when the character is read by the user program. Recognized when IEXTEN and ISIG are set, and the system supports job control, and then not passed as input.
```

The default Python interpreter ignores it and so does ipython. It is an unwanted surprise to the user. I understand that it can be unset via `stty dsusp undef` but it goes against the idea of having sensible defaults without configuration.

**Comment by thomasballinger** [comment]
(information also in edit above) It seems `$python` does ignore Ctrl-Y if set up to use readline, but if not using readline Python properly suspends on ctrl-y (try <C-Y><Enter> since input is line-buffered). Since we're pretending to use readline (ie readline keys work) it seems reasonable to ignore this. I don't know how to do this yet.

**Comment by thomasballinger** [comment]
~~~
+        attrs = termios.tcgetattr(self.in_stream)
+        attrs[-1][11] = 0
+        termios.tcsetattr(self.in_stream, termios.TCSANOW, attrs)
~~~
does it, need to write that with constants and make sure it works across platforms.

**Comment by thomasballinger** [comment]
Here's the new version: https://github.com/thomasballinger/curtsies/compare/disable-ctrl-y

Thoughts? Seems like there should be a better way to detect whether dsusp is a thing on a system - presumably we don't need to shell out to stty? Neither my OSX nor linux Python installs have `termios.VDSUSP` defined, so that's no good.

**Comment by amjith** [comment]
:+1: 

I tried the branch of curtsies and Ctrl-Y doesn't suspend bpython anymore and it does paste stuff from my yank-ring. 

I'm all in favor of adding it to the mainline. :)

**Comment by thomasballinger** [comment]
I'm trying to get perspective on this, I've posted http://stackoverflow.com/questions/29024007/disable-dsusp-in-python and tweeted about it. I'd love to hear if this is normal and if checking for `sys.platform` being `"darwin"` is the right way to predict it.

**Comment by jonathanslenders** [comment]
For what it's worth, in prompt-toolkit I use this context manager to turn a terminal into raw mode.
https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/terminal/vt100_input.py#L303

```python
return attrs & ~(termios.ECHO | termios.ICANON | termios.IEXTEN | termios.ISIG)
```

As far as I understand, by removing the ISIG flag, all keys are send to the application itself, so none of them will be able to send a signal. This also means that Ctrl-Z needs to be handled manually in order to suspend the process. See:

https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/key_binding/bindings/basic.py#L287

https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/interface.py#L455

cc @amjith

**Comment by thomasballinger** [comment]
Thanks @jonathanslenders, that's helpful to see. I'll look into this, at some point I decided to use cbreak for stdin in Curtsies instead of raw, because at the time I thought it simplified something about signal handling - probably because it wouldn't have to be changed for running user code. Doing things your way looks like a better option, but I don't think I'm going to do this today, and might even add the other version as a temp fix.

Anyone in the thread coming to Pycon in Montreal in a month? I'd love to talk about terminals and REPLs with you!

**Comment by amjith** [comment]
Yes! I'll be at PyCon. I'd love to talk REPLs with you. :)

**Comment by thomasballinger** [comment]
@amjith Great! See you then.

If I switch to raw mode, in order to present the same interface Curtsies would need to send the signal, but I'd really rather it returned a SuspendEvent. Because this would break the API, I'm going to use the if `sys.platform == 'darwin'` hack and put using raw on the (long) list of ideas I have for a next version.

**Comment by jquast** [comment]
This program may assist in debugging special keys https://github.com/pexpect/pexpect/blob/master/tools/display-terminalinfo.py

**Comment by thomasballinger** [comment]
@jquast That's terrific, thanks! The tables alone are pretty useful.

**Comment by thomasballinger** [comment]
@jquast https://asciinema.org/a/17702

**Comment by jquast** [comment]
neat, that effect reminds of me an old virus for MS-DOS that randomly shifted the upper/lowercase of the video memory, so even dir.exe would display EleeT.ExE-speaj
