### ISSUE TITLE
<F1> Does Not Work in GNOME Terminal

### ISSUE THREAD

**Issue by StevenXL** [bpython/bpython#522]
The <F1> key does not work in GNOME Terminal. Instead of bpython's help, <F1> pulls up the GNOME Terminal Manual.

**Comment by thomasballinger** [comment]
This is interesting - it's because GNOME terminal captures F1 for help. I'd say it's not our problem except it's the help key that we tell users to press on startup - not very pleasant to have the first thing you try not work. Detecting GNOME terminal seems out of the quesiton - should we change the key?

**Comment by thomasballinger** [comment]
I think help should be on another key, like `ctrl-?`.

**Comment by StevenXL** [comment]
I'm not sure if there is a key that most programs have standardized on for a help key. If there isn't, then I do think it should be changed.  I like `ctrl-?`, but that's two keys. Can we switch it to F2 and move the current F2 and F3 over one spot? (F4 is not used right now).

**Comment by sebastinas** [comment]
We could just refer to http://askubuntu.com/questions/37313/how-do-i-deactivate-f1-and-f10-keybindings-in-gnome-terminal in http://docs.bpython-interpreter.org/tips.html

**Comment by sebastinas** [comment]
This is now documented. See http://bpython-interpreter.org/known-issues-and-faq.html.
