### ISSUE TITLE
Upload to Pastebin is not working

### ISSUE THREAD

**Issue by StevenXL** [bpython/bpython#524]
bpython's upload to pastebin feature is not working for me. I get the following error:

Upload failed: hostname 'bpaste.net' doesn't match either of '*.qabana.nl', 'qabana.nl'

**Comment by sebastinas** [comment]
Please install requests[security]. That's necessary for requests to have SNI support with old Python 2.7.x versions.

**Comment by thomasballinger** [comment]
Trying this today on a fresh Ubuntu 14.04 with the last stable release of bpython (not including @sebastinas's fixes above) I can reproduce this:
~~~
$ sudo apt-get update
$ sudo apt-get install python-pip python-greenlet
$ sudo pip install bpython
$ bpython --version
bpython version 0.14.1 on top of Python 2.7.6
(C) 2008-2015 Bob Farrell, Andreas Stuehrk et al. See AUTHORS for detail.
~~~
Unfortunately, pip install of requests[security] failed after this with
~~~
$ sudo pip install requests[security]
Requirement already satisfied (use --upgrade to upgrade): requests[security] in /usr/lib/python2.7/dist-packages
  Installing extra requirements: 'security'
Cleaning up...
~~~
In this situation, pastebin worked once I ran
~~~
sudo apt-get install libssl-dev libffi-dev python-dev
sudo pip install --upgrade pip
sudo pip install --upgrade requests[security]
~~~

**Comment by StevenXL** [comment]
Thanks - I'll add that to the README.

**Comment by thomasballinger** [comment]
@StevenXL I'm not sure we should have installation instructions for every platform in the README, and I suspect @sebastinas will feel we shouldn't. I wonder if the documentation should have this, or even an external blog - It would certainly help a lot of people who try to install bpython and aren't sure what to do when it doesn't work, but we don't want to be responsible for maintaining installation instructions for every platform.

Anyone have thoughts? Maybe an external repo I could maintain with installation instructions? I do think it's worth paying attention to this because bpython can be a really helpful learning tool for the very same folks that aren't likely to know what to do in these situation.

**Comment by sebastinas** [comment]
In fact, it's already documented in README.rst:

```
If you are using Python 2 before 2.7.7, the following dependency is also
required:

* requests[security]
```

**Comment by thomasballinger** [comment]
Right, I meant describing what to do if `pip install requests[security]` fails as above.

**Comment by sebastinas** [comment]
Ah, okay, in that case I don't think that bpython's README is the place to document pip usage. We could add something to http://bpython-interpreter.org/downloads.html as we did for the Mac OS X cffi issue.
