### ISSUE TITLE
add operate-and-get-next (C-o)

### ISSUE THREAD

**Issue by thomasballinger** [bpython/bpython#631]
As it works in [bash](http://linux.die.net/man/1/bash). If we're not getting multiline history anytime soon, this will help a bit.

**Comment by PeriGK** [comment]
Hi @thomasballinger,

I am afraid I dont quite understand the requirement? could you please provide me with a usage scenario?

Thanks,
P.

**Comment by thomasballinger** [comment]
Hi @PeriGK, sure! Thanks for your interest in the issue, please let me know if you want any help with this.

When you enter a multiline command, or several lines that go together, and then want to run them again, right now you have to hit up arrow enough times to get back to that line in history, then go back that many times again to get the next line, then go back again, once for each line. Ctrl-o

Ctrl-o gets swallowed in bash on OSX by default, so if you're on a mac and want to try it out try running `stty -iexten` in the terminal first or ssh into a linux server to see it.

Here's a [CPython issue about adding it](https://bugs.python.org/issue22228), looks like it hasn't been merged yet. This isn't really related to us trying to implement it, it just might be a useful description of the feature.
 
[this asciinema shows use of ctrl-o](https://asciinema.org/a/90139)

I'm imagining we add a key to `bpython/curtsiesfrontend/repl.py` that is the same as hitting entry for the current command, except that the current history index isn't reset back to the end.

**Comment by PeriGK** [comment]
Hi @thomasballinger ,

Thanks for the hints. Ok I think I can start working on the bug. 

Could you please let me know how do we understand a multiline command? Will it be that it just ends with "\"?

Here is my understanding till now, please let me know if I am totally off with something:
- I will need to go through the history list(self.history), lets say backwards.
- When the first "\" or any other multiline indicator is seen, I will be creating a string till "\" is not there. - Of course, I will concatenate the last-before-the-first-backslash-string seen, as this is the last line of the multiline command.
- All this work(or at least most of it) will be happening inside BaseRepl class. The only way to execute the above logic, will be to hit Ctrl+o in the keyboard.

Thanks,
P.

**Comment by thomasballinger** [comment]
Yep, I agree BaseRepl is the place for this. However, this does not require detecting multiline commands. Ctrl-o doesn't treat lines that are part of mutliline commands any differently than single line commands, it only runs the current line and brings up the next command in history.

You might try out ctrl-o to get a feel for how it works. Here's an online shell (type `bash` first) that you can use to try this out: https://www.tutorialspoint.com/unix_terminal_online.php

I would say that ctrl-o requires
* saving the current history index
* running the current command
* selecting the next line of history

**Comment by PeriGK** [comment]
Ok I think it is starting getting clearer now. Though, from what I can see is the following.
For example I am writing the command:
`echo "Foo"` and then hit Ctrl+o. 

It will run the echo command, and then set it out again, ready for input. In our case, instead of the last command(which is the same command which just executed), we want the one-before-the-last. Am I getting this right?

Cheers,
P.

**Comment by PeriGK** [comment]
Let me provide an example of what I am understanding so that we are sure we are on the same page.

So this is the history list: ["echo 1", "echo 2", "ls -la ~"].

I am navigating with the up-button to the "echo 2" command(index = 1). When I am hitting Ctrl+o, it will run the command and then bring the command "ls -la ~" ready for input.

**Comment by thomasballinger** [comment]
Yep, that's the behavior we're looking for.

    $ echo 1
    1
    $ echo 2
    2
    $ ls -la ~
    Lots of files
    <up arrow twice>
    $ echo 2
    <ctrl-o instead of enter>
    $ ls -la ~

**Comment by PeriGK** [comment]
Hi @thomasballinger,

I am having some issues testing the changes, could you please confirm I am deploying the changes correctly?

- I am running `python3 setup.py build` on the root level of the project.
- A "build" folder is created and I am navigating under build/bpython. Then I am running `python3 cli.py`.
- I am testing the behavior in there.

The problem is that I can see my changes being reflected in there, so I would like to eliminate the potential causes one-by-one.

Thanks,
P.

**Comment by thomasballinger** [comment]
@PeriGK,

You want to be running `python3 -m bpython` from one level up (/build/lib) instead. You're currently running the curses-based version of bpython, which probably isn't the one you're editing. You can tell the difference because the curses version fills the whole screen, while the curtsies version doesn't.

The workflow I use is running `pip install -e .` while in that directory. This installs this version of bpython, so that just running `bpython` (not `python3 bpython, just `bpython`) will run the new code.

**Comment by PeriGK** [comment]
I am currently struggling to print the next command in the buffer...All the obvious solutions failed. :) I will pick it up again in a few days, as I will be having limited time due to professional reasons.

Just FYI

**Comment by thomasballinger** [comment]
Sounds good. Also feel free to push what you have and open an incomplete pull request, which will make it easier to ask questions. I'm also on irc on freenode in #bpython, in case you'd rather chat about this there.

It might be helpful to see up arrow, https://github.com/bpython/bpython/blob/master/bpython/curtsiesfrontend/repl.py#L854
Which does some similar history stuff.
