### ISSUE TITLE
[bug?] bpython can't find modules under virtualenvwrapper environment.

### ISSUE THREAD

**Issue by hdarwin** [bpython/bpython#632]
is this bug or not supported feature??
```
root@box:~# mkvirtualenv test
root@box:~# workon test
(test) root@box:~# pip install module_need_for_test
(test) root@box:~# bpython
>>> import module_need_for_test
>>> ImportError: No module named module_need_for_test
(test) root@box:~# ipython
>>> import module_need_for_test
>>> 
```

**Comment by thomasballinger** [comment]
You'll need to install bpython in that virtual environment. IPython does some funny sys.path munging to prevent needing to install it in the venv, but the docs suggest you install it there if something goes wrong because its kind of a hack. Currently bpython doesn't implement this hack. I think there's an old issue to do with this, but in my mind it's not out of the question.
