### ISSUE TITLE
Executing only `raise` throws SystemError in Python 3

### ISSUE THREAD

**Issue by dputtick** [bpython/bpython#659]
Kind of a small weird error:

In Python 2, if you just execute `raise` you get the same exception in the vanilla repl and bpython:
```
>>> raise
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    raise
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType
```
In Python 3, bpython gives this:
```
>>> raise
SystemError: PyEval_EvalFrameEx returned NULL without setting an error
```
Whereas in the normal repl:
```
>>> raise
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: No active exception to reraise
```

**Comment by Trundle** [comment]
This issue was fixed in CPython, see http://bugs.python.org/issue27558.

The CPython issue and commits (https://hg.python.org/cpython/rev/ba45fbb16499) mention threads, but it seems also possible to reproduce the issue with greelets:

```python
from greenlet import greenlet

def raise_():
    raise

g = greenlet(raise_)
g.switch()
```

Running ander a CPython version with the fix applied, bpython produces the expected output:

```
bpython version 0.17.dev8 on top of Python 3.5.2+ /tmp/_env/bin/python
>>> raise
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    raise
RuntimeError: No active exception to reraise
```

Note that older Python version (for example, 3.3) seem to produce yet another variant under bpython:

```
>>> raise
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    raise
SystemError: error return without exception set
```
