### ISSUE TITLE
[FEATURE REQUEST] Automatically insert closing bracket

### ISSUE THREAD

**Issue by logileifs** [bpython/bpython#695]
This is a feature request to automatically insert a closing bracket, curly braces or quotes when typing the opening one. For example: type ( and bpython automatically inserts )

This saves a lot of typing when trying out some code in the interactive shell

**Comment by thomasballinger** [comment]
Hm, a couple issues I can think of:

We'd need to keep considering the function with closed parens the active one - right now adding a close paren makes the function docstring and arg highlighting stop showing and it'd be some work to change this. Actually adding the close paren isn't bad.

More serious are some multiline editing issues: with a paren already closed, how do we know whether to run the line on enter or to go to the next line.

These make this feature unlikely, but discussion welcome :)

Closing the issue for now because there are no plans for this at this point.
