### ISSUE TITLE
Weird performance bug when printing

### ISSUE THREAD

**Issue by BenWiederhake** [bpython/bpython#704]
Steps to reproduce:
- Start bpython3
- Paste the following snippet so that it only runs after pressing the return key manually (i.e., with only one `\n` after the `print(i)`), and observe the execution speed.
- Paste the following snippet so that it runs immediately (i.e., with *two* `\n` after the `print(i)`), and observe the execution speed.

```python
for i in range(100):
    print(i)

```

Expected behavior: Both execute at the same speed

Actual behavior: If the last `\n` is entered manually, execution speed is *significantly* lower.

This seems to be true for all kinds of outputs during loops, including output from valued statements (i.e., `i * i`).

**Comment by thomasballinger** [comment]
I think this is due to optimizing the second case by using a much larger buffer when code is run due to a paste event, but this is worth looking into. I prefer the unbuffered (but slower) write behavior for interactive sessions; the thought was that for an interactive interpreter, lag was worse than running slowly.

**Comment by BenWiederhake** [comment]
> lag was worse than running slowly.

I agree whole-heartedly.  Also, I see a lot more lag than two versions ago, but the reported issue is the only case where I can really demonstrate it.

**Comment by thomasballinger** [comment]
Closing the difference between these two modes as wontfix, but if interactive behavior is frustratingly slow that's worth opening another bug for.
