### ISSUE TITLE
How can I delete a line code?

### ISSUE THREAD

**Issue by youyiqin** [bpython/bpython#763]
```
>>> for i in [1,2,3]:
...   print(i)
...   d
...   |  

```
How can I delete 'd'?
Thanks!

**Comment by benkrig** [comment]
Is this what you're going for?

From the README:
* Rewind.  This isn't called "Undo" because it would be misleading, but "Rewind"
  is probably as bad. The idea is that the code entered is kept in memory and
  when the Rewind function is called, the last line is popped and the entire
  session is re-evaluated.  Use **\<control-R\>** to rewind.

**Comment by youyiqin** [comment]
Thanks.I know.
