### ISSUE TITLE
Fills RAM until it makes my PC/Laptop locked

### ISSUE THREAD

**Issue by obayhan** [bpython/bpython#866]
Memory usage increases until it fills my RAM and locks my PC/Laptop

Here is my screen record to show it:

[https://www.youtube.com/watch?v=B3_0iTqkqkg](https://www.youtube.com/watch?v=B3_0iTqkqkg)

CPU architecture: 64 bit Intel
OS:Linux/Manjaro/KDE
Python version: 3.8.6
bpython version: 0.18, 0.19, 0.20 (didnt tested with older versions)

Same thing appears with my laptop too.

**Comment by sebastinas** [comment]
I suspect this has to do with the new module discovery code. Could you maybe produce a log with strace so that we can see what it tries to crawl and if ends up in a loop?

**Comment by domdfcoding** [comment]
I've encountered this too. I couldn't get strace to output to a file without hanging, but here's the last bit of the output before I stopped it after 5 minutes: https://gist.github.com/domdfcoding/0aea640a1ae3fefa0d046bfdd9ea70c2

The output was pretty much the same before this.

In those 5 minutes the memory usage the memory usage rose from 20MB to over 100MB. When I first noticed this it had been running for about an hour and ended up using 13GB of memory.

**Comment by sebastinas** [comment]
Thanks. Looks like we have to try to deal with mount points or at least blacklist some paths - including wine specific paths, /sys, /proc.

**Comment by obayhan** [comment]
Sorry for late response. Same strace output with @domdfcoding 

`stat("./PlayOnLinux's virtual drives/HOI/drive_c/users/ozgur/Desktop/workspaces/AndroidStudio/AndroidTVappTutorial/app/build/generated/not_namespaced_r_class_sources/debug/r/androidx/drawerlayout", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0`

**Comment by robobenklein** [comment]
Still appears to be an issue for me, I use a variety of tools including Proton and Lutris.

Steam seemed to have an infinite depth wine prefix scanning problem in https://github.com/ValveSoftware/steam-for-linux/issues/7372#issuecomment-808434073 which may be related.

I think there should be some upper hard limit at which point no more modules are discovered, say if more than 500MB of memory is consumed then the scanning should be disabled since something clearly went wrong.
