### ISSUE TITLE
Copying text broken into multiple lines by terminal copies the line breaks.

### ISSUE THREAD

**Issue by keystroke3** [bpython/bpython#944]
When using mouse to highlight text in bpython shell and copy it using default terminal bindings, the line breaks are copied as well. For example: 
```python
>>> fake.paragraph()
'Long charge pull somebody right technology prevent. Tree option among whose. Sort head land involve same actually address. Finally th
ere baby past travel of generation add.'
>>> p = 'Finally th
  File "<input>", line 1
    p = 'Finally th
                   ^
SyntaxError: EOL while scanning string literal
>>> ere baby past travel
```
In the above case, the line `Finally there baby past travel of generation add.` was broken to the next terminal line. When copying using mouse highlight and terminal's copy keyboard shortcut,  in my case `ctrl + shift + c`, the line break was copied as well.

Outside of bpython and using the default python shell, I am able to highlight and copy the text without the line breaks. Is there a configuration I am supposed to set?

**Comment by thomasballinger** [comment]
Unfortunately bpython is manually doing the line break here based on the current width of the terminal to (among other things?) avoid reflows when resizing. I agree this is bad behavior. When I wrote it I couldn't figure out how to do it correctly on all terminal emulators since the reflow behavior is different. https://ballingt.com/rich-terminal-applications-2/ has some of my thoughts at the time.

I think this is possible to do correctly, especially if we gave up on terminal resizing working well. More manual checking of how many lines tall the terminal is could be helpful, moving the cursor and querying its position to check how lines are currently wrapped. Calculating history gets tricky after a resize, since the scrollback buffer can't be examined the same way, but if there were an option to sacrifice history behavior for better line breaks I think most people would prefer this.

I don't have any plans to do this, but I think there is another set of compromises to make that does this correctly. I think the place to start with this would be https://github.com/bpython/curtsies, probably creating a new Window implementation in https://github.com/bpython/curtsies/blob/main/curtsies/window.py after making some more fundamental changes to FSArray, maybe a new class since this behavior is pretty different.

**Comment by keystroke3** [comment]
It's unfortunate that this is a blocked issue. I can look at it and see if I can offer any help with it. I use terminals for 90% of my work, so I would be happy to work on it to fix this bug.  I am closing the issue as there's no solution at the moment, and and no current plans to fix it. We can reopen it when a solution is on the horizon or is being discussed. Thank you for your response.
